In [ ]:
def increment_counter(counter):
    i = len(counter) - 1
    while i >= 0:
        if counter[i] < 25:
            counter[i] += 1
            return counter
        counter[i] = 0
        i -= 1
    counter.insert(0, 0)
    return counter

def is_valid_key(key, k):
    for i in range(len(key) - k + 1):
        if all(char == key[i] for char in key[i:i+k]):
            return False
    return True

def key_generator(n, k):
    counter = [0] * n

    while True:
        key = [chr(digit + 65) for digit in counter]  # Converts counter digits to uppercase letters
        if is_valid_key(key, k):
            counter = increment_counter(counter)
            yield ''.join(key)
        else:
            counter = increment_counter(counter)

# Example usage
n = 10  # Key size
k = 3   # Maximum consecutive characters
generator = key_generator(n, k)

# Generate the next key
next_key = next(generator)
print(next_key)

# Generate another key
another_key = next(generator)
print(another_key)

In [20]:
from __future__ import division, print_function, absolute_import

import numpy as np

def fAndG(W, X):
    assert isinstance(W, np.ndarray)
    dim = W.shape
    assert len(dim) == 2
    W_rows = dim[0]
    W_cols = dim[1]
    assert isinstance(X, np.ndarray)
    dim = X.shape
    assert len(dim) == 2
    X_rows = dim[0]
    X_cols = dim[1]
    assert W_cols == X_rows

    functionValue = (W).dot(X)
    gradient = np.einsum('ik, jl', W, np.eye(X_cols, X_cols))

    return functionValue, gradient

In [21]:
def checkGradient(W, X):
    # numerical gradient checking
    # f(x + t * delta) - f(x - t * delta) / (2t)
    # should be roughly equal to inner product <g, delta>
    t = 1E-6
    delta = np.random.randn(3, 3)
    f1, _ = fAndG(W, X + t * delta)
    f2, _ = fAndG(W, X - t * delta)
    f, g = fAndG(W, X)
    print('approximation error', np.linalg.norm((f1 - f2) / (2*t) - np.tensordot(g, delta, axes=2)))

In [22]:
def generateRandomData():
    W = np.random.randn(2, 3)
    X = np.random.randn(3, 4)

    return W, X

In [25]:
W, X = generateRandomData()
functionValue, gradient = fAndG(W, X)
print('functionValue = ', functionValue)
print('gradient = ', gradient)

gradient.shape

functionValue =  [[ 1.8238319   3.12866519 -1.68386798 -3.48356168]
 [ 2.86443458  1.64454758  0.77534399 -1.22635369]]
gradient =  [[[[ 0.58413949  0.          0.          0.        ]
   [-0.86482308  0.          0.          0.        ]
   [-2.41932732  0.          0.          0.        ]]

  [[ 0.          0.58413949  0.          0.        ]
   [ 0.         -0.86482308  0.          0.        ]
   [ 0.         -2.41932732  0.          0.        ]]

  [[ 0.          0.          0.58413949  0.        ]
   [ 0.          0.         -0.86482308  0.        ]
   [ 0.          0.         -2.41932732  0.        ]]

  [[ 0.          0.          0.          0.58413949]
   [ 0.          0.          0.         -0.86482308]
   [ 0.          0.          0.         -2.41932732]]]


 [[[-0.85331602  0.          0.          0.        ]
   [-1.26688406  0.          0.          0.        ]
   [-0.44898994  0.          0.          0.        ]]

  [[ 0.         -0.85331602  0.          0.        ]
   [ 0. 

(2, 4, 3, 4)

In [ ]:
print('numerical gradient checking ...')
checkGradient(W, X)

In [33]:
A = np.random.randn(2,4)
B = np.random.randn(3,4)

np.kron(A,B).shape

(6, 16)

In [37]:
A = np.diag([1,2])
A

array([[1, 0],
       [0, 2]])

In [39]:
B = [[1,2],[3,4]]
B

[[1, 2], [3, 4]]

In [40]:
A @ B

array([[1, 2],
       [6, 8]])

In [41]:
A * B

array([[1, 0],
       [0, 8]])

In [43]:
np.diag(np.diag(A))

array([[1, 0],
       [0, 2]])

In [52]:
A = np.random.randn(2,2)
A

array([[-1.62125267,  1.77374981],
       [-0.4726807 ,  1.41600304]])

In [53]:
B = np.random.randn(2,2)
B

array([[0.59106348, 0.37731101],
       [0.34496551, 0.22113453]])

In [54]:
A * B

array([[-0.95826324,  0.66925533],
       [-0.16305854,  0.31312716]])

In [55]:
np.diag(A) @ np.diag(B)

-0.6451360793976687

In [58]:
np.diag(A) @ np.diag(B)

-0.6451360793976687